#  ____            ___        __            _ ____  _            _
# | __ )  __ _  __| \ \      / /__  _ __ __| | __ )| | ___   ___| | _____ _ __
# |  _ \ / _` |/ _` |\ \ /\ / / _ \| '__/ _` |  _ \| |/ _ \ / __| |/ / _ \ '__|
# | |_) | (_| | (_| | \ V  V / (_) | | | (_| | |_) | | (_) | (__|   <  __/ |
# |____/ \__,_|\__,_|  \_/\_/ \___/|_|  \__,_|____/|_|\___/ \___|_|\_\___|_|
#
# (C) 2018 by surva network | https://github.com/survanetwork

# Language of the plugin messages
# Possible options are: en (English), de (German), fr (French), ru (Russian), tr (Turkish), id (Indonesian)
language: "en"

# List of the blocked words
badwords:
  - "fuck"
  - "shit"
  - "bitch"
  - "cunt"
  - "nigger"
  - "ass"
  - "asshole"
  - "fucker"
  - "fucking"
  - "bitchass"
  - "motherfucker"
  - "fuckin"
  - "nigga"
  - "damn"
  - "hell"

# Ignore spaces in messages when checking for swear words / spam
ignorespaces: true

# Minimum time between chat messages in seconds
waitingtime: 2

# Percentage of uppercase chars in a message required to trigger caps checker
uppercasepercentage: 0.75

# Minimum amount of chars in a message required to activate caps checker (to avoid blocking HI, OK, etc.)
minimumchars: 3

# After how many violations against the chat filter, a player should be kicked/banned - set to 0 to disable
# Violations are reset after a server restart
violations:
  kick: 0
  ban: 0
  resetafterkick: true # reset violations after kick (this disables banning if kick-count is lower)
